openapi: 3.0.4
info:
  title: "rmcluster server"
  version: 0.0.1

paths:
  /announce:
    get:
      summary: Announce a new node
      parameters:
        - name: port
          in: query
          required: true
          schema:
            type: integer
        - name: ip
          in: query
          required: false
          schema:
            type: string
      responses:
        200:
          description: "Successful announce"
          content:
            application/json:
              schema:
                type: object
                properties:
                  interval:
                    type: float
                    description: "The number of seconds the client should wait between announces."