/*
 * rmcluster server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
	"github.com/wk-y/rama-swap/tracker"
)

type DefaultAPI struct {
}

// Get /announce
// Announce a new node
func (api *DefaultAPI) AnnounceGet(c *gin.Context) {
	// Your handler implementation
	tracker.DefaultTracker.Announce(c)
}
